### ISSUE TITLE
heroku run rails db:migrateのエラーを解消する。

### ISSUE THREAD

**Issue by yukiHaga** [yukiHaga/regex-hunting#81]
## 概要
現状、`heroku run rails db:migrate`を実行するとエラーが発生する。おそらくタイムゾーン関係のエラーである。もしくは、time型のカラム(result_time)に整数値を入れているのが原因なのかもしれない。どっちみし、開発環境でゲーム機能が完全にできないと、検証の試用がないので、ゲーム機能ができたら取り掛かる。

## やること
- [ ] エラーの内容を解析する。
```
OB^[OB^[OB^[OBD, [2021-12-19T03:29:15.418025 #4] DEBUG -- :    (1.1ms)  SELECT pg_try_advisory_lock(25
79139626601131685)
D, [2021-12-19T03:29:15.431056 #4] DEBUG -- :    (1.5ms)  SELECT "schema_migrations"."version" FROM "s
chema_migrations" ORDER BY "schema_migrations"."version" ASC
I, [2021-12-19T03:29:15.432353 #4]  INFO -- : Migrating to CreateGameManagements (20211122134323)
== 20211122134323 CreateGameManagements: migrating ============================
-- create_table(:game_managements)
D, [2021-12-19T03:29:15.436652 #4] DEBUG -- :    (1.2ms)  BEGIN
D, [2021-12-19T03:29:15.451480 #4] DEBUG -- :    (10.5ms)  CREATE TABLE "game_managements" ("id" bigse
rial primary key, "difficulty_level" integer DEFAULT 0 NOT NULL, "game_result" integer DEFAULT 0 NOT N
ULL, "result_time" time DEFAULT 0 NOT NULL, "play_date" date NOT NULL, "user_id" bigint NOT NULL, "cre
ated_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL, CONSTRAINT "fk_rails_d3b6174981"
FOREIGN KEY ("user_id")
  REFERENCES "users" ("id")
)
D, [2021-12-19T03:29:15.452738 #4] DEBUG -- :    (1.0ms)  ROLLBACK
D, [2021-12-19T03:29:15.454256 #4] DEBUG -- :    (1.3ms)  SELECT pg_advisory_unlock(257913962660113168
5)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "result_time" is of type time without time zone but default expre
ssion is of type integer
HINT:  You will need to rewrite or cast the expression.
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgres
ql/database_statements.rb:92:in `exec'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgres
ql/database_statements.rb:92:in `block (2 levels) in execute'
```
- [ ] マイグレーションファイルの内容をpostgreSQLのDBに反映させる。

## 受け入れ条件
- [ ] マイグレーションファイルの内容が反映されている。

## 参考記事
- [column is of type timestamp without time zone but expression is of type integer](https://stackoverflow.com/questions/32034274/column-is-of-type-timestamp-without-time-zone-but-expression-is-of-type-integer)
- [Rails + Heroku 環境で、レコードのタイムゾーンがずれていることに気が付いた際に確認したいこと & リカバリ方法](https://qiita.com/tetsuya/items/e0fd25fc3da2615d1cb2)
- [42804: column is of type timestamp without time zone but expression is of type text #630](https://github.com/npgsql/efcore.pg/issues/630)

**Comment by yukiHaga** [comment]
マイグレーションファイルの順番が正しくないために、バグが起こっていました。
無事解決済みです。
